CREATE USER MTS IDENTIFIED BY MTS;

GRANT SELECT_CATALOG_ROLE      TO MTS;
GRANT CREATE JOB               TO MTS;
GRANT CREATE MATERIALIZED VIEW TO MTS;
GRANT CREATE PROCEDURE         TO MTS;
GRANT CREATE SEQUENCE          TO MTS;
GRANT CREATE SESSION           TO MTS;
GRANT CREATE SYNONYM           TO MTS;
GRANT CREATE TABLE             TO MTS;
GRANT CREATE TRIGGER           TO MTS;
GRANT CREATE TYPE              TO MTS;
GRANT CREATE VIEW              TO MTS;
GRANT QUERY REWRITE            TO MTS;
GRANT UNLIMITED TABLESPACE     TO MTS;
ALTER USER MTS DEFAULT ROLE ALL;